# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Research
    url: research/
    weight: 11
  - name: Awards & Talks
    url: /awards_talks/
    weight: 12
  - name: Teaching & Services
    url: teaching_services/
    weight: 20
  - name: Miscellaneous
    url: miscellaneous/
    weight: 30